-- Environment placeholders
SET CATALOG = ''cfa_demo'';
SET SCHEMA_GOLD = ''gold'';
SET SCHEMA_SEM = ''semantic_analytics'';
SET GROUP_ANALYSTS = ''cfa_sc_analysts'';
SET WAREHOUSE_NAME = ''serverless_sql_wh'';

SELECT ''${CATALOG}'' AS catalog,
       ''${SCHEMA_GOLD}'' AS schema_gold,
       ''${SCHEMA_SEM}'' AS schema_sem,
       ''${GROUP_ANALYSTS}'' AS group_analysts,
       ''${WAREHOUSE_NAME}'' AS warehouse_name;

USE CATALOG `${CATALOG}`;

GRANT USAGE ON CATALOG `${CATALOG}` TO `group ${GROUP_ANALYSTS}`;
GRANT USAGE ON SCHEMA `${CATALOG}`.`${SCHEMA_SEM}` TO `group ${GROUP_ANALYSTS}`;

REVOKE ALL PRIVILEGES ON SCHEMA `${CATALOG}`.`${SCHEMA_GOLD}` FROM `group ${GROUP_ANALYSTS}`;
REVOKE SELECT ON ALL TABLES IN SCHEMA `${CATALOG}`.`${SCHEMA_GOLD}` FROM `group ${GROUP_ANALYSTS}`;
REVOKE SELECT ON FUTURE TABLES IN SCHEMA `${CATALOG}`.`${SCHEMA_GOLD}` FROM `group ${GROUP_ANALYSTS}`;

GRANT SELECT ON ALL VIEWS IN SCHEMA `${CATALOG}`.`${SCHEMA_SEM}` TO `group ${GROUP_ANALYSTS}`;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA `${CATALOG}`.`${SCHEMA_SEM}` TO `group ${GROUP_ANALYSTS}`;
